version: '3.8'

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: sqlserver
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Omran@1998
    ports:
      - "1433:1433"
    networks:
      - mynetwork
    healthcheck:
      test: ["CMD", "sqlcmd", "-S", "localhost", "-U", "sa", "-P", "Omran@1998", "-Q", "SELECT 1"]
      interval: 10s
      retries: 5
      timeout: 5s
      start_period: 30s

  candidateportal:
    build: .
    container_name: candidateportal
    depends_on:
      - sqlserver
    ports:
      - "5000:80"
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge
